name: capsule
description: Capsule App.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #  fl_chart: ^0.65.0
  readmore: ^2.1.0
  hidable: ^1.0.6
  flutter_screenutil: ^5.9.0
  provider: ^6.0.5
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.7
  local_auth: ^2.1.7
  lottie: ^2.6.0
  smooth_page_indicator: ^1.1.0
  pinput: ^3.0.1

  #localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # firebase
  firebase_core: ^2.24.2
  firebase_database: ^10.3.0
  firebase_auth: ^4.11.0
  cloud_firestore: ^4.10.0
  firebase_messaging: ^14.7.2

  http: ^1.1.0

  flutter_local_notifications: ^16.1.0
  # rating bar
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.0.0


  image_picker: ^1.0.4
  enough_giphy_flutter: ^0.4.0
  emoji_picker_flutter: ^1.6.3
  flutter_riverpod: ^2.4.8
  flutter_sound: ^9.2.13
  cached_network_image: ^3.3.0
  cached_video_player: ^2.0.4
  swipe_to: ^1.0.4
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6


flutter:


  uses-material-design: true
  generate: true


  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-VariableFont_wght.ttf

  assets:
    - assets/images/
    - assets/images/person/
    - assets/images/doctors_ui/
    - assets/icons/
    - assets/lottie/
